# fly.toml app configuration file generated for anecdotes-ci-cd on 2024-04-16T14:06:05+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'anecdotes-ci-cd'
primary_region = 'syd'

[build]

[env]
	PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
